version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: next-dashboard-db
    environment:
      POSTGRES_USER: nieves
      POSTGRES_PASSWORD: moonlight4321
      POSTGRES_DB: gg
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
